# Build Stage
FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN go build -o agent cmd/agent/main.go

# Run Stage
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/agent .
# No EXPOSE needed because Agent only initiates outbound traffic
CMD ["./agent"]