# Build Stage
FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod download
# Build the binary specifically for the 'server' main file
RUN go build -o server cmd/server/main.go

# Run Stage (Small Image)
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/server .
EXPOSE 8080
CMD ["./server"]